### ISSUE TITLE
Add Docker compose example to wiki

### ISSUE THREAD

**Issue by melroy89** [Taisun-Docker/taisun#8]
Add to:
https://github.com/Taisun-Docker/taisun/wiki/Linux#running-taisun

Example:
```yml
version: '3.7'

services:
  taisun:
    image: linuxserver/taisun
    container_name: taisun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    network_mode: bridge
    restart: unless-stopped
```
